VERSION 0.8

refine-admin-base:
    FROM ../../../+node
    WORKDIR /app
    COPY --dir package.json pnpm-lock.yaml /app
    DO ../../../+USEPNPM
    RUN pnpm install --silent
    COPY --dir .eslintrc.cjs index.html prettier.config.js public src tsconfig.app.json tsconfig.json tsconfig.node.json vite.config.ts /app

update-lock-file:
    FROM ../../../+node
    WORKDIR /app
    COPY --dir package.json /app
    DO ../../../+USEPNPM
    RUN pnpm install --silent
    SAVE ARTIFACT pnpm-lock.yaml AS LOCAL pnpm-lock.yaml

live:
    FROM +refine-admin-base
    DO ../../../+APT_GET_UPDATE_INSTALL --packages=procps
    CMD pnpm run dev --host 0.0.0.0
    ARG --required ref
    ARG extra_ref
    COPY ../../../.certs+local-certificate/ca.crt /tmp/local-cert
    ENV NODE_EXTRA_CA_CERTS=/tmp/local-cert
    SAVE IMAGE --push ${ref} ${extra_ref}

lint:
    FROM +refine-admin-base
    COPY --dir test /app
    RUN pnpm run lint

build:
    FROM +refine-admin-base
    RUN pnpm build --logLevel silent
    SAVE ARTIFACT dist
    SAVE ARTIFACT node_modules
