#!/bin/sh

# Navigate to the commitlint tools directory
cd tools/commitlint

# Run commitlint to check the commit message
npx commitlint --edit "$1"
if [ $? -ne 0 ]; then
  echo "Commit message does not follow conventional commit standards. Commit aborted."
  exit 1
fi
