repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.4.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: commitlint
        name: commit-msg
        stages: [commit-msg]
        entry: tools/commitlint-warning.sh
        language: node
        additional_dependencies: ['@commitlint/cli', '@commitlint/config-conventional']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
