apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dap.fullname" . }}-signer-eddsa
  labels:
    {{- include "dap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.signerEddsa.autoscaling.enabled }}
  replicas: {{ .Values.signerEddsa.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.signerEddsa.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dap.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.signerEddsa.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.signerEddsa.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.signerEddsa.securityContext | nindent 12 }}
          image: "{{ .Values.signerEddsa.image.repository }}:{{ .Values.signerEddsa.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.signerEddsa.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.signerEddsa.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
            failureThreshold: 50
          resources:
            {{- toYaml .Values.signerEddsa.resources | nindent 12 }}
      {{- with .Values.signerEddsa.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.signerEddsa.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.signerEddsa.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
