VERSION 0.8


live:
    FROM ../../+rust
    RUN cargo install cargo-watch
    COPY Cargo.lock Cargo.toml .
    RUN mkdir -p src && touch src/main.rs
    RUN cargo fetch
    COPY --keep-ts --dir src .
    RUN cargo build --bin signer-eddsa
    CMD ["cargo", "watch", "-x", "run --bin signer-eddsa"]
    ARG --required ref
    SAVE IMAGE --push ${ref}

test:
    FROM ../../+rust
    COPY Cargo.lock Cargo.toml .
    RUN mkdir -p src && touch src/main.rs
    RUN cargo fetch
    COPY --keep-ts --dir src .
    RUN --mount=type=cache,target=/app/target cargo test
