apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-access
  namespace: default
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ingress-nginx-controller
  - to:
    - podSelector:
        matchLabels:
          app: dap-nest
    - podSelector:
        matchLabels:
          app: dap-doc
    - podSelector:
        matchLabels:
          app: dap-signer-eddsa
