title = "gitleaks config"

[extend]

# You can set the mode to protect or audit
mode = "protect"

# Custom rules can be defined here
[[rules]]
	description = "generic AWS secret rule"
	regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
	tags = ["key", "AWS"]

# Add paths to ignore
[[pathAllowlist]]
	description = "Ignore .yarn directory"
	path = '''^\.yarn/'''

[[pathAllowlist]]
	description = "Ignore node_modules directory"
	path = '''^node_modules/'''

[[pathAllowlist]]
	description = "Ignore pnpm store directory"
	path = '''^pnpm-store/'''

[[pathAllowlist]]
	description = "Ignore .pnpm directory"
	path = '''^\.pnpm/'''

# Add rules to allow files to be ignored
[allowlist]
	paths = [
		"^\\.yarn/",
		"^node_modules/",
		"^pnpm-store/",
		"^\\.pnpm/"
	]

# This will be a list of regexes to ignore certain commits
[[commitAllowlist]]
	description = "Ignore commits with specific messages"
	regex = '''(?i)^(merge|fix)'''
