{{- $root := . -}}
{{- range $key, $val := .Values }}
{{- if and (hasKey $val "service") (or (not (hasKey $val "enabled")) (eq true $val.enabled)) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dap.fullname" $root }}-{{ $val.name }}
  labels:
    {{- include "dap.labels" $root | nindent 4 }}
    app.kubernetes.io/name: {{ include "dap.fullname" $root }}-{{ $val.name }}
spec:
  {{- if or (not (hasKey $val "autoscaling")) (not $val.autoscaling.enabled) }}
  replicas: {{ $val.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dap.selectorLabels" $root | nindent 6 }}
      app.kubernetes.io/name: {{ include "dap.fullname" $root }}-{{ $val.name }}
  template:
    metadata:
      {{- with $val.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dap.selectorLabels" $root | nindent 8 }}
        app.kubernetes.io/name: {{ include "dap.fullname" $root }}-{{ $val.name }}
    spec:
      {{- with $val.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $val.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $key }}
          securityContext:
            {{- toYaml $val.securityContext | nindent 12 }}
          image: "{{ $val.image.repository }}:{{ $val.image.tag | default $root.Chart.AppVersion }}"
          imagePullPolicy: {{ $val.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $val.service.port }}
              protocol: TCP
          env:
            {{- if $val.env }}
            {{- range $envKey, $envVal := $val.env }}
            - name: {{ $envKey }}
              value: {{ $envVal | quote }}
            {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ default "/" $val.service.probePath }}
              port: http
            periodSeconds: 8
            failureThreshold: 35
          readinessProbe:
            httpGet:
              path: {{ default "/" $val.service.probePath }}
              port: http
            periodSeconds: 8
            failureThreshold: 35
          resources:
            {{- toYaml $val.resources | nindent 12 }}
      {{- with $val.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $val.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $val.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
