VERSION 0.8


live:
    FROM ../+src
    RUN cd server && cargo build --bin eddsa-server
    CMD ["cargo", "watch", "-x", "run --bin eddsa-server"]
    ARG --required ref
    SAVE IMAGE --push ${ref}

test:
    FROM ../+src
    WORKDIR /app/server
    RUN --mount=type=cache,target=/app/target cargo test
